/**
 * The tool registry.
 *
 * This is built in exactly ONE place and every entry point calls this function.
 * tests/entrypoint-parity.test.js fails the build if any entry point is ever
 * handed a different set of tools or a different schema for the same tool —
 * because the day the web UI can do something the API cannot, there are two
 * assistants with different powers and nobody notices until one of them does
 * something the other would have refused.
 *
 * Note what is absent: there is no delete tool, of any kind, for any resource.
 * Not for workflows, not for executions, not for credentials.
 */

import { searchNodes, getNodeSchema, catalogMeta, isWriteOperation, isOpaqueNode, getNode } from './nodeIndex.js';
import { validateWorkflow } from './validate.js';
import { assessExecution } from './assess.js';
import { remember, activeFacts } from './memory.js';
import { askPeer, listPeers } from './peers.js';
import { fetchPublicUrl, BlockedUrlError } from './web.js';
import { assessReadiness, summariseReadiness } from './readiness.js';

/** Actions that need explicit confirmation: sending and spending. Nothing else. */
export const APPROVAL_REQUIRED = {
  ACTIVATE: 'activate_workflow',
  ENABLE_WRITES: 'enable_write_nodes',
  // Asking a peer what it already knows is free. Telling it to go and find out
  // is spending — at the far end, on the same person's money.
  COMMISSION_RESEARCH: 'commission_research',
  // Reading a public API is a read. Anything that is not a read — a POST, a
  // PUT, a DELETE at someone else's URL — is sending, and sending needs a yes
  // whether the recipient is a person or an endpoint.
  SEND_REQUEST: 'send_http_request',
};

/**
 * Was THIS action approved, for THIS thing?
 *
 * Approvals used to be bare strings: "activate_workflow" meant every
 * activation in the turn, not the one that was shown to the user. So a yes for
 * one workflow let a different one go live in the same turn — and a model that
 * has been told "you may activate" will use that on whatever it is holding.
 * The gate was decorative in exactly the case it exists for.
 *
 * An approval may now name its target. A bare string still works, because that
 * is what the browser sends today and a refusal that used to succeed reads as
 * a regression to whoever is looking at it — but anything that names a target
 * only unlocks that target.
 */
export function approvalCovers(approvals, action, target = null) {
  for (const granted of approvals ?? []) {
    if (typeof granted === 'string') {
      if (granted === action) return true;
      continue;
    }
    if (granted?.action !== action) continue;
    if (granted.target === undefined || granted.target === null) return true;
    if (target !== null && String(granted.target) === String(target)) return true;
  }
  return false;
}

const ok = (data) => ({ ok: true, ...data });
const fail = (error, extra = {}) => ({ ok: false, error, ...extra });

/**
 * @param {object} ctx
 * @param {object} ctx.n8n         n8n client, or null if not configured
 * @param {object} ctx.store
 * @param {string[]} ctx.approvals action keys the user has explicitly approved this turn
 * @param {(s:string)=>void} ctx.onStatus
 */
export function buildToolRegistry(ctx) {
  const { n8n = null, store, approvals = [], prefs = {}, onStatus = () => {}, fetchImpl = globalThis.fetch, resolveHost = undefined } = ctx;

  const needsN8n = () =>
    fail('No n8n connection is configured. Paste your n8n base URL and API key in Settings first.');

  const tools = [
    {
      name: 'search_nodes',
      say: (a) => `looking for something that can ${a.query ?? 'do that'}`,
      description:
        'Search the n8n node index for nodes matching a query. Returns each node type with its resource/operation discriminators. ALWAYS call this before using any node — never write a node type from memory.',
      parameters: {
        type: 'object',
        properties: {
          query: { type: 'string', description: 'What the node should do, e.g. "slack send message" or "google sheets append".' },
          limit: { type: 'number', description: 'Max results, default 12.' },
        },
        required: ['query'],
      },
      handler: async ({ query, limit }) => {
        const results = searchNodes(query, { limit: limit ?? 12 });
        if (!results.length) {
          return ok({
            results: [],
            note: `Nothing in the index matches "${query}". The index holds ${catalogMeta().nodeCount} nodes. Do not invent a node type — try different words, or tell the user this node is not available.`,
          });
        }
        return ok({ results });
      },
    },

    {
      name: 'get_node_schema',
      say: (a) => `reading the real settings for ${prettyNode(a.nodeType)}`,
      description:
        'Get the EXACT parameter definitions for a node + resource + operation, as generated by n8n itself. You must call this for every node you plan to use before writing its parameters. Inventing a parameter name will be rejected by the validator.',
      parameters: {
        type: 'object',
        properties: {
          nodeType: { type: 'string', description: 'Full node type, e.g. "n8n-nodes-base.slack".' },
          resource: { type: 'string', description: 'Resource discriminator, e.g. "message".' },
          operation: { type: 'string', description: 'Operation discriminator, e.g. "post".' },
        },
        required: ['nodeType'],
      },
      handler: async ({ nodeType, resource, operation }) => {
        const schema = getNodeSchema({ type: nodeType, resource: resource ?? null, operation: operation ?? null });
        if (!schema.found) return fail(schema.error, { available: schema.available });

        // Trim: the model needs the type text for the operations it asked
        // about, and sending all of them for a node like Slack is 100KB.
        const trimmed = schema.operations.slice(0, 3).map((o) => ({
          ...o,
          typeDefinition: o.typeDefinition?.slice(0, 24000) ?? null,
        }));
        return ok({ ...schema, operations: trimmed, truncated: schema.operations.length > 3 });
      },
    },

    {
      name: 'list_credentials',
      say: () => 'checking which accounts you have connected',
      description:
        'List the credentials that exist in the n8n instance (names, ids and types only — never secrets). Use a real credential id; never invent one.',
      parameters: { type: 'object', properties: {} },
      handler: async () => {
        if (!n8n) return needsN8n();
        try {
          const res = await n8n.listCredentials();
          const items = (res?.data ?? res ?? []).map((c) => ({ id: c.id, name: c.name, type: c.type }));
          return ok({ credentials: items });
        } catch (e) {
          return fail(`Could not list credentials: ${e.message}`);
        }
      },
    },

    {
      name: 'check_workflow_ready',
      say: () => 'checking whether it can actually run',
      description:
        'Whether a workflow can actually RUN, which is a different question from whether it saved. Finds nodes with no credential attached, credentials pointing at ids that do not exist here, values still left as placeholders, disabled nodes, and a missing trigger. Call it before telling anyone a build is finished — "it saved" and "it will work at 7am" are not the same sentence.',
      parameters: {
        type: 'object',
        properties: {
          id: { type: 'string', description: 'A workflow id to read from n8n and check.' },
          workflow: { type: 'object', description: 'Or the workflow object itself, to check before saving.' },
        },
      },
      handler: async ({ id, workflow }) => {
        let target = workflow;
        if (!target && id) {
          if (!n8n) return needsN8n();
          try {
            target = await n8n.getWorkflow(id);
          } catch (e) {
            return fail(`Could not read workflow ${id}: ${e.message}`);
          }
        }
        if (!target) return fail('Which workflow? Give me an id, or the workflow itself.');

        // The instance's real credential list turns "has something attached"
        // into "points at something that exists". Without it the check is
        // weaker, and it says so rather than implying otherwise.
        let credentials = null;
        if (n8n) {
          try {
            const res = await n8n.listCredentials();
            credentials = (res?.data ?? res ?? []).map((c) => ({ id: c.id, name: c.name, type: c.type }));
          } catch {
            credentials = null;
          }
        }

        const readiness = assessReadiness(target, { credentials });
        return ok({ ...readiness, summary: summariseReadiness(readiness) });
      },
    },

    {
      name: 'read_api',
      say: (a) => `reading ${(() => { try { return new URL(a.url).hostname; } catch { return 'the documentation'; } })()}`,
      description:
        "Read a page or call an API on the public internet. This is how you find out what an API actually looks like instead of guessing at it or stopping: fetch its documentation, fetch its OpenAPI spec, or call an endpoint and look at the real response. Use it before writing HTTP Request node parameters for a service you do not already know for certain. GET and HEAD are free and need no permission. Any other method is sending, and sending needs the owner's yes.",
      parameters: {
        type: 'object',
        properties: {
          url: { type: 'string', description: 'A full http or https URL on the public internet.' },
          method: { type: 'string', description: 'GET by default. HEAD is also free. Anything else needs approval first.' },
          headers: { type: 'object', description: 'Headers to send, e.g. an API key the user has given you FOR THIS REQUEST. Never invent one and never reuse a credential from n8n — n8n does not hand them out.' },
          body: { type: 'string', description: 'Request body, only for methods that take one.' },
        },
        required: ['url'],
      },
      handler: async ({ url, method = 'GET', headers = {}, body = null }) => {
        // Asked without one, say which thing is missing. "undefined is not a
        // URL" is true and useless, and it is what the model reads back.
        if (!url || typeof url !== 'string') return fail('Which URL? Give me the full address, including https://.');
        const verb = String(method).toUpperCase();

        // Reading is a read. Anything else is a request that arrives at
        // somebody's server as an action, and that is the same category as
        // sending a message — it needs a yes, whoever the recipient is.
        const host = (() => { try { return new URL(url).host; } catch { return null; } })();
        if (!['GET', 'HEAD'].includes(verb) && !approvalCovers(approvals, APPROVAL_REQUIRED.SEND_REQUEST, host)) {
          return {
            ok: false,
            needsApproval: APPROVAL_REQUIRED.SEND_REQUEST,
            approvalTarget: host,
            error: `A ${verb} to ${String(url).slice(0, 120)} is a request that does something at the other end, not a read. I need you to confirm before I send it.`,
          };
        }

        try {
          const res = await fetchPublicUrl(url, { method: verb, headers, body, timeoutMs: 12_000, fetchImpl, resolve: resolveHost });
          return ok({
            url: res.url,
            status: res.status,
            contentType: res.contentType,
            redirectedThrough: res.redirectedThrough,
            json: res.json,
            // Enough to learn an API from, not so much that one page eats the
            // whole request budget. Everything here is billed as input on every
            // later step of the same turn.
            text: res.text ? res.text.slice(0, 12_000) : null,
            truncated: res.truncated || (res.text?.length ?? 0) > 12_000,
          });
        } catch (e) {
          if (e instanceof BlockedUrlError) return fail(`I will not fetch that: ${e.message}`, { blocked: true });
          return fail(e.message);
        }
      },
    },

    {
      name: 'get_credential_schema',
      say: (a) => `checking what a ${a.type ?? 'credential'} needs`,
      description:
        'The exact fields a credential type needs, so you can tell the owner precisely what to create rather than describing it vaguely. You cannot create credentials yourself and you must never ask for a secret in conversation — say the type, a name, and which fields to fill, and they will do it in n8n where secrets belong.',
      parameters: {
        type: 'object',
        properties: { type: { type: 'string', description: 'The credential type name, e.g. httpHeaderAuth, httpQueryAuth, googleApi.' } },
        required: ['type'],
      },
      handler: async ({ type }) => {
        if (!n8n) return needsN8n();
        if (!type) return fail('Which credential type?');
        try {
          const schema = await n8n.credentialSchema(type);
          const props = schema?.properties ?? {};
          return ok({
            type,
            fields: Object.entries(props).map(([name, spec]) => ({
              name,
              label: spec?.displayName ?? name,
              required: Array.isArray(schema?.required) ? schema.required.includes(name) : undefined,
              secret: Boolean(spec?.typeOptions?.password),
            })),
            howToCreate: `In n8n: Credentials → New → search "${type}" → fill the fields above → Save. Then tell me the name you gave it and I will use it. Do not paste the secret to me; it belongs in n8n, not in a conversation.`,
          });
        } catch (e) {
          return fail(`Could not read the schema for "${type}": ${e.message}. The type name may be wrong — list_credentials shows the types already in use.`);
        }
      },
    },

    {
      name: 'list_workflows',
      say: () => 'looking at what you already have',
      description: 'List workflows in the n8n instance.',
      parameters: {
        type: 'object',
        properties: {
          limit: { type: 'number' },
          active: { type: 'boolean', description: 'Filter to only active or only inactive workflows.' },
        },
      },
      handler: async ({ limit, active }) => {
        if (!n8n) return needsN8n();
        try {
          const asked = limit ?? 30;
          const res = await n8n.listWorkflows({ limit: asked, active: active ?? null });
          const items = (res?.data ?? []).map((w) => ({
            id: w.id,
            name: w.name,
            active: w.active,
            isArchived: w.isArchived ?? false,
            updatedAt: w.updatedAt,
            nodeCount: w.nodes?.length ?? null,
          }));
          // n8n hands back a cursor when there is another page. Without saying
          // so, "you have 30 workflows" is confidently wrong on an instance
          // with 200 — and nothing in the answer would hint at it.
          const more = Boolean(res?.nextCursor);
          return ok({
            workflows: items,
            more,
            note: more
              ? `This is the first ${items.length} only — there are more. Say so rather than implying this is everything, and ask for a bigger limit or a filter if the whole list matters.`
              : null,
          });
        } catch (e) {
          return fail(`Could not list workflows: ${e.message}`);
        }
      },
    },

    {
      name: 'get_workflow',
      say: () => 'opening that workflow',
      description: 'Fetch one workflow in full, including its nodes and connections.',
      parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] },
      handler: async ({ id }) => {
        if (!n8n) return needsN8n();
        try {
          return ok({ workflow: await n8n.getWorkflow(id) });
        } catch (e) {
          return fail(`Could not fetch workflow ${id}: ${e.message}`);
        }
      },
    },

    {
      name: 'validate_workflow',
      say: () => 'checking every setting is real before saving',
      description:
        'Validate workflow JSON before saving it. Checks node types, parameter names against the real schemas, required parameters, ungrounded picker values, and the connection graph. ALWAYS call this before save_workflow.',
      parameters: {
        type: 'object',
        properties: { workflow: { type: 'object', description: 'The full workflow JSON: { name, nodes, connections }.' } },
        required: ['workflow'],
      },
      handler: async ({ workflow }) => {
        const result = await validateWorkflow(workflow);
        return ok(result);
      },
    },

    {
      name: 'ground_options',
      say: (a) => `fetching your actual ${a.resource ?? 'options'} from ${prettyNode(a.nodeType)}`,
      description:
        'Get the REAL list of values for a picker parameter (Slack channels, Google Sheets tabs, and so on) by running a temporary read-only probe workflow in n8n against the credential. Use this instead of guessing any id. The probe is archived afterwards and never deletes anything.',
      parameters: {
        type: 'object',
        properties: {
          nodeType: { type: 'string' },
          resource: { type: 'string' },
          operation: { type: 'string', description: 'A read-only list operation, e.g. "getAll".' },
          credentialType: { type: 'string' },
          credentialId: { type: 'string' },
          parameters: { type: 'object', description: 'Extra parameters the list operation needs.' },
        },
        required: ['nodeType', 'credentialType', 'credentialId'],
      },
      handler: async (args) => {
        if (prefs.allowProbes === false) {
          return fail(
            'Probe workflows are switched off in settings, so I cannot read the real list of values. I will not guess an id — pick the value in n8n and tell me what it is.',
          );
        }
        return runProbe({ n8n, store, onStatus, prefs, ...args });
      },
    },

    {
      name: 'save_workflow',
      say: (a) => (a.mode === 'update' ? 'saving a new version, keeping the old one' : 'saving it, switched off for now'),
      description:
        'Create a new workflow (always inactive) or update an existing one. Updating snapshots the current version first so it is always recoverable. Never destroys anything.',
      parameters: {
        type: 'object',
        properties: {
          mode: { type: 'string', description: '"create" or "update".' },
          id: { type: 'string', description: 'Required when mode is "update".' },
          workflow: { type: 'object' },
          tags: {
            type: 'array',
            items: { type: 'string' },
            description: 'Tag names to attach, created if they do not exist. Use "system:<short-name>" for every workflow belonging to the same system.',
          },
          reason: { type: 'string', description: 'Why this change is being made — recorded with the snapshot.' },
          overwriteChangesSince: {
            type: 'string',
            description:
              'Only after the user has said to go ahead: the version you were working from, when the workflow has changed in n8n since you read it. Overwriting somebody\'s hand-edit is a decision they make, not one you make.',
          },
        },
        required: ['mode', 'workflow'],
      },
      handler: async ({ mode, id, workflow, tags, reason, overwriteChangesSince }) => {
        if (!n8n) return needsN8n();

        const validation = await validateWorkflow(workflow);
        if (!validation.valid) {
          return fail('Refusing to save: the workflow does not validate.', { validation });
        }

        // n8n rejects unknown top-level keys on write.
        const payload = {
          name: workflow.name,
          nodes: workflow.nodes,
          connections: workflow.connections ?? {},
          settings: workflow.settings ?? {},
        };

        /**
         * Whether the thing that was just saved can actually run.
         *
         * A workflow was once designed correctly, validated, saved and reported
         * as done — with a placeholder document id and an unset credential,
         * both named honestly in the summary. It still sat in n8n looking
         * exactly like a finished one, and switching it on would have failed at
         * 07:00 with nobody watching. Saved and runnable are two facts.
         */
        const readinessOf = async (saved) => {
          try {
            let credentials = null;
            try {
              const res = await n8n.listCredentials();
              credentials = (res?.data ?? res ?? []).map((c) => ({ id: c.id, name: c.name, type: c.type }));
            } catch {
              credentials = null;
            }
            const readiness = assessReadiness(saved ?? workflow, { credentials });
            return { ...readiness, summary: summariseReadiness(readiness) };
          } catch {
            // A readiness check that throws must never lose a successful save.
            return null;
          }
        };

        /** Tagging is reported separately: the save can succeed and this not. */
        const applyTags = async (workflowId) => {
          const wanted = tags ?? workflow.tags;
          if (!wanted?.length || !workflowId) return null;
          try {
            return await n8n.setWorkflowTags(workflowId, wanted);
          } catch (e) {
            return { tags: [], confirmed: false, error: `Saved, but tagging failed: ${e.message}` };
          }
        };

        try {
          if (mode === 'create') {
            /**
             * The same workflow, saved twice, is two workflows — and this system
             * never deletes, so the spare is there for good.
             *
             * A turn that times out after the save lands but before the answer
             * arrives leaves the model believing it failed; resuming, it saves
             * again. Nobody is watching the second one, it has the same
             * schedule, and it does the same work twice a day forever.
             *
             * Matched on the shape, not just the name: a genuinely different
             * workflow that happens to share a title is still a new one.
             */
            const fingerprint = (w) => JSON.stringify({
              nodes: (w?.nodes ?? []).map((n) => ({ name: n.name, type: n.type, parameters: n.parameters ?? {} })),
              connections: w?.connections ?? {},
            });
            try {
              // Paged, because the copy being looked for is not necessarily on
              // the first page — and a duplicate created because we did not
              // look far enough is worse than no check at all, since nothing
              // here can delete it afterwards. Bounded, and it says so if it
              // stopped early rather than implying it saw everything.
              const PAGES = 10;
              let cursor = null;
              let already = null;
              let seen = 0;
              let ranOut = false;
              for (let page = 0; page < PAGES; page++) {
                const res = await n8n.listWorkflows({ limit: 50, cursor });
                const batch = res?.data ?? [];
                seen += batch.length;
                already = batch.find((w) => w?.name === payload.name && w?.nodes && fingerprint(w) === fingerprint(payload));
                cursor = res?.nextCursor ?? null;
                if (already || !cursor || !batch.length) break;
                if (page === PAGES - 1 && cursor) ranOut = true;
              }
              if (ranOut) {
                onStatus(`Checked ${seen} workflows for an existing copy and there are more; carrying on.`);
              }
              if (already) {
                // The tags are still outstanding work: the request was "make
                // this exist, tagged", and only the first half was already
                // done. Skipping the create must not skip the rest of the job.
                const tagged = await applyTags(already.id);
                return ok({
                  created: false,
                  id: already.id,
                  confirmed: true,
                  active: Boolean(already.active),
                  validation,
                  tagged,
                  readiness: await readinessOf(already),
                  alreadyExisted: true,
                  note: `This exact workflow is already in n8n as ${already.id} ("${already.name}"), so I did not make a second copy. If you wanted a separate one, change something about it or give it a different name.`,
                });
              }
            } catch {
              // Not being able to check is no reason to refuse to save. Worst
              // case is the behaviour that existed before this check.
            }

            onStatus('Creating workflow (inactive)…');
            const res = await n8n.createWorkflow(payload);
            const tagged = await applyTags(res.workflow?.id);
            const readiness = await readinessOf(res.readBack ?? res.workflow);
            return ok({
              created: true,
              id: res.workflow?.id,
              confirmed: res.confirmed,
              active: false,
              validation,
              tagged,
              readiness,
              fieldsNotAccepted: res.fieldsNotAccepted,
              note: res.confirmed
                ? `Created and read back from n8n. It is inactive until you approve activating it.${readiness && !readiness.ready ? ` ${readiness.summary}` : ''}`
                : "Created, but reading it back did not confirm it — I can't yet promise it is there.",
            });
          }

          if (mode === 'update') {
            if (!id) return fail('mode "update" needs the workflow id.');
            onStatus('Snapshotting the current version before changing it…');
            const current = await n8n.getWorkflow(id);

            /**
             * Somebody may have opened n8n and changed this while he was
             * thinking.
             *
             * Reading a workflow, working for forty seconds and writing it
             * back is a lost update. Their change goes into a snapshot they do
             * not know exists — nothing was deleted, technically, and the
             * effect is that their work vanished with no word about it. That
             * is the failure this whole project is built to avoid, arriving
             * through the one door left open.
             *
             * n8n stamps a versionId on every save. When the workflow being
             * written carries one, it says which version the edit was based
             * on, and a mismatch means somebody else got there first. Nothing
             * is refused when there is no version to compare — building
             * something from scratch has nobody to race.
             */
            const basedOn = workflow?.versionId ?? null;
            if (basedOn && current?.versionId && basedOn !== current.versionId && overwriteChangesSince !== basedOn) {
              return fail(
                `"${current.name}" changed in n8n since I read it — I was working from version ${basedOn} and it is now ${current.versionId}. ` +
                  'Somebody edited it in the editor while I was building. I have not written anything, because that would have replaced their work with mine. ' +
                  'Tell me to go ahead and I will overwrite it (the version that is there now is snapshotted first, so it can be brought back), or ask me to read it again and redo the change on top of theirs.',
                { changedUnderneath: true, basedOnVersion: basedOn, currentVersion: current.versionId, workflowId: id },
              );
            }
            const snap = await store.snapshot({
              workflowId: id,
              name: current?.name ?? null,
              workflow: current,
              reason: reason ?? 'before update',
            });

            // n8n's PUT replaces the whole workflow. Anything the caller did not
            // resend is gone — so pinned test data and stored state are carried
            // over unless they are being deliberately changed. Losing them is a
            // quiet form of deleting something.
            const carried = { ...payload };
            for (const key of ['pinData', 'staticData']) {
              const next = workflow[key] ?? current?.[key];
              if (next !== undefined) carried[key] = next;
            }

            const res = await n8n.updateWorkflow(id, carried, { snapshotId: snap.id });
            const tagged = await applyTags(id);
            const readiness = await readinessOf(res.readBack ?? workflow);
            return ok({
              updated: true,
              id,
              snapshotId: snap.id,
              confirmed: res.confirmed,
              validation,
              tagged,
              readiness,
              fieldsNotAccepted: res.fieldsNotAccepted,
              keptFromPreviousVersion: ['pinData', 'staticData'].filter((k) => carried[k] !== undefined && workflow[k] === undefined),
              note: `Previous version saved as snapshot ${snap.id}; it can be restored at any time.${readiness && !readiness.ready ? ` ${readiness.summary}` : ''}`,
            });
          }

          return fail(`Unknown mode "${mode}".`);
        } catch (e) {
          return fail(`Save failed: ${e.message}`);
        }
      },
    },

    {
      name: 'dry_run_workflow',
      say: () => 'testing it with everything that sends turned off',
      description:
        'Test a workflow WITHOUT touching real systems: every write-capable node is disabled, test data is pinned on the trigger, and the workflow is run. Reports what each node produced and exactly what the disabled write nodes WOULD have received.',
      parameters: {
        type: 'object',
        properties: {
          id: { type: 'string', description: 'Workflow id to dry run.' },
          pinData: { type: 'object', description: 'Test data to pin, keyed by trigger node name.' },
        },
        required: ['id'],
      },
      handler: async ({ id, pinData }) => dryRun({ n8n, store, onStatus, prefs, id, pinData }),
    },

    {
      name: 'list_failed_executions',
      say: () => 'looking for anything that broke',
      description: 'List recent failed executions across the instance, newest first. Use this to find out what broke.',
      parameters: {
        type: 'object',
        properties: { limit: { type: 'number' }, workflowId: { type: 'string' } },
      },
      handler: async ({ limit, workflowId }) => {
        if (!n8n) return needsN8n();
        try {
          const res = await n8n.listExecutions({ status: 'error', limit: limit ?? 10, workflowId: workflowId ?? null });
          const items = (res?.data ?? []).map((e) => ({
            id: e.id,
            workflowId: e.workflowId,
            workflowName: e.workflowData?.name ?? null,
            status: e.status,
            startedAt: e.startedAt,
          }));
          const more = Boolean(res?.nextCursor);
          return ok({
            failures: items,
            more,
            note: more ? `The newest ${items.length} only — there are older failures beyond this. Do not describe this as everything that has broken.` : null,
          });
        } catch (e) {
          return fail(`Could not list executions: ${e.message}`);
        }
      },
    },

    {
      name: 'get_execution',
      say: () => 'reading what actually happened on that run',
      description: 'Read one execution in full, including the error and which node failed.',
      parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] },
      handler: async ({ id }) => {
        if (!n8n) return needsN8n();
        try {
          const execution = await n8n.getExecution(id);
          const assessment = assessExecution({ execution });
          return ok({ execution: summariseExecution(execution), assessment });
        } catch (e) {
          return fail(`Could not read execution ${id}: ${e.message}`);
        }
      },
    },

    {
      name: 'set_workflow_active',
      say: (a) => (a.active ? 'switching it on' : 'switching it off'),
      description:
        'Activate or deactivate a workflow. Deactivating is always allowed. ACTIVATING a workflow that contains write-capable nodes requires the user to approve first, because activating it means it will start sending things.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' }, active: { type: 'boolean' } },
        required: ['id', 'active'],
      },
      handler: async ({ id, active }) => {
        if (!n8n) return needsN8n();
        try {
          if (active) {
            const wf = await n8n.getWorkflow(id);
            const writers = writeNodesIn(wf);
            if (writers.length && !approvalCovers(approvals, APPROVAL_REQUIRED.ACTIVATE, id)) {
              return {
                ok: false,
                needsApproval: APPROVAL_REQUIRED.ACTIVATE,
                // Which workflow, so the yes can be about something specific
                // rather than about activation in general.
                approvalTarget: id,
                error:
                  `Activating "${wf.name}" (${id}) would let it send things for real via: ${writers.join(', ')}. ` +
                  'I need you to confirm before I do that.',
                writeNodes: writers,
              };
            }
          }
          const res = await n8n.setActive(id, active);
          return ok({
            requested: active,
            actual: res.actual,
            confirmed: res.confirmed,
            note: res.confirmed
              ? `Read back from n8n as active=${res.actual}.`
              : `n8n accepted the change but reads back as active=${res.actual}. I cannot confirm it took effect.`,
          });
        } catch (e) {
          return fail(`Could not change activation: ${e.message}`);
        }
      },
    },

    {
      name: 'archive_workflow',
      say: () => 'putting it away — not deleting it',
      description:
        'Retire a workflow by deactivating and archiving it. This is the ONLY way to retire something — nothing is ever deleted, and it can be restored.',
      parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] },
      handler: async ({ id }) => {
        if (!n8n) return needsN8n();
        try {
          return ok(await n8n.archiveWorkflow(id));
        } catch (e) {
          return fail(`Could not archive: ${e.message}`);
        }
      },
    },

    {
      name: 'restore_snapshot',
      say: (a) => `putting back the version saved as ${a.snapshotId ?? 'a snapshot'}`,
      description:
        'Put a previous version of a workflow back. Every update snapshots what it replaced, and this is what makes that snapshot worth having — without it the history can be listed and never used. The restore itself snapshots what it replaces, so undoing an undo is possible too.',
      parameters: {
        type: 'object',
        properties: {
          snapshotId: { type: 'string', description: 'From list_snapshots.' },
          reason: { type: 'string', description: 'Why this is being rolled back — recorded with the new snapshot.' },
        },
        required: ['snapshotId'],
      },
      handler: async ({ snapshotId, reason }) => {
        if (!n8n) return needsN8n();
        if (!snapshotId) return fail('Which snapshot? list_snapshots shows them.');

        const snap = await store.getSnapshot(snapshotId);
        if (!snap) return fail(`No snapshot called ${snapshotId}. list_snapshots shows what there is.`);
        if (!snap.workflow?.nodes) {
          return fail(`Snapshot ${snapshotId} holds no workflow — it was taken when the workflow could not be read, so there is nothing in it to put back.`);
        }
        if (!snap.workflowId) return fail(`Snapshot ${snapshotId} does not say which workflow it belongs to.`);

        try {
          // What is there now goes into a snapshot first. An undo that cannot
          // itself be undone is just another one-way door.
          const current = await n8n.getWorkflow(snap.workflowId);
          const undo = await store.snapshot({
            workflowId: snap.workflowId,
            name: current?.name ?? null,
            workflow: current,
            reason: `before restoring ${snapshotId}${reason ? `: ${reason}` : ''}`,
          });

          const res = await n8n.updateWorkflow(snap.workflowId, snap.workflow, { snapshotId: undo.id });
          const readBack = res.readBack ?? (await n8n.getWorkflow(snap.workflowId).catch(() => null));
          return ok({
            restored: true,
            id: snap.workflowId,
            fromSnapshot: snapshotId,
            snapshotId: undo.id,
            confirmed: res.confirmed,
            readiness: await (async () => {
              try {
                const creds = await n8n.listCredentials();
                return assessReadiness(readBack ?? snap.workflow, {
                  credentials: (creds?.data ?? creds ?? []).map((c) => ({ id: c.id, name: c.name, type: c.type })),
                });
              } catch {
                return null;
              }
            })(),
            note: `Put back the version from ${snap.at}. What was there instead is saved as ${undo.id}, so this can be undone as well.`,
          });
        } catch (e) {
          return fail(`Could not restore ${snapshotId}: ${e.message}`);
        }
      },
    },

    {
      name: 'unarchive_workflow',
      say: (a) => `bringing ${a.id ?? 'it'} back out of the archive`,
      description:
        'Bring an archived workflow back into the list. Archiving is how things are retired here instead of deleting them, which only means anything if it can be undone. It comes back switched off, whatever it was before.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
      },
      handler: async ({ id }) => {
        if (!n8n) return needsN8n();
        if (!id) return fail('Which workflow?');
        try {
          const res = await n8n.unarchiveWorkflow(id);
          return ok({
            ...res,
            note: res.confirmed
              ? 'Back in the list, and still switched off — bringing something back is not the same as starting it.'
              : 'n8n accepted it but reading it back did not confirm it came out of the archive.',
          });
        } catch (e) {
          return fail(`Could not unarchive ${id}: ${e.message}`);
        }
      },
    },

    {
      name: 'resolve_finding',
      say: () => 'marking that one as dealt with',
      description:
        'Mark an open finding as resolved, once the workflow it refers to has actually run successfully. Requires the id of a SUCCESSFUL execution as evidence — you may not close a finding because you believe you fixed it, only because you watched it work.',
      parameters: {
        type: 'object',
        properties: {
          findingId: { type: 'string' },
          executionId: { type: 'string', description: 'A successful execution of the same workflow, read back from n8n.' },
        },
        required: ['findingId', 'executionId'],
      },
      handler: async ({ findingId, executionId }) => {
        // Named plainly, before anything can interpolate "undefined" into a
        // sentence and hand back an error nobody can act on.
        if (!findingId) return fail('Which finding? Send the id from the list of what needs a look.');
        if (!executionId) return fail('Which execution proves it works? I do not close anything without one.');
        if (!n8n) return needsN8n();

        // The same rule as every other success sentence in this system: an
        // execution, read back, or no claim. Believing it is fixed is not
        // evidence that it is.
        let execution;
        try {
          execution = await n8n.getExecution(executionId);
        } catch (e) {
          return fail(`Could not read execution ${executionId}, so I cannot close anything on the strength of it: ${e.message}`);
        }

        const assessment = assessExecution({ execution });
        if (assessment.verdict !== 'worked') {
          return fail(
            `Execution ${executionId} is "${assessment.verdict}", not a success, so it is not evidence that this is fixed. ${assessment.detail}`,
            { assessment },
          );
        }

        const open = await store.listFindings({ status: 'open' });
        const finding = open.find((f) => f.id === findingId);
        if (!finding) return fail(`No open finding with id ${findingId}.`);

        if (finding.workflowId && execution.workflowId && String(finding.workflowId) !== String(execution.workflowId)) {
          return fail(
            `That execution belongs to workflow ${execution.workflowId}, but the finding is about ${finding.workflowId}. A success somewhere else is not evidence about this.`,
          );
        }

        const updated = await store.updateFinding(findingId, {
          status: 'resolved',
          resolvedAt: new Date().toISOString(),
          resolvedBy: `execution ${executionId}`,
        });

        return ok({
          finding: updated,
          evidence: assessment.evidence,
          note: `Closed on the evidence of execution ${executionId}. The record is kept and can be reopened.`,
        });
      },
    },

    {
      name: 'list_snapshots',
      say: () => 'looking at earlier versions',
      description: 'List saved snapshots of previous workflow versions, so a change can be reviewed or rolled back.',
      parameters: { type: 'object', properties: { workflowId: { type: 'string' } } },
      handler: async ({ workflowId }) => ok({ snapshots: (await store.listSnapshots(workflowId ?? null)).map(({ workflow, ...rest }) => rest) }),
    },
    {
      name: 'remember',
      say: (a) => `noting that ${String(a.fact ?? '').slice(0, 60)}`,
      description:
        'Save something worth knowing about this user or their setup for future conversations — a preference, which channel or sheet is the real one, a constraint they stated. Use it when you learn something you would otherwise have to ask again. Do not save transient details about one request.',
      parameters: {
        type: 'object',
        properties: {
          fact: { type: 'string', description: 'One short sentence, written so it still makes sense months later.' },
          supersedes: { type: 'string', description: 'Id of an existing memory this corrects.' },
        },
        required: ['fact'],
      },
      handler: async ({ fact, supersedes }) => {
        try {
          const res = await remember(store, fact, { source: 'learned', supersedes: supersedes ?? null });
          return ok(res);
        } catch (e) {
          return fail(e.message);
        }
      },
    },

    {
      name: 'ask_peer',
      say: (a) => `asking ${a.peer ?? 'the research assistant'}`,
      description:
        'Ask another AI a question when the specification is incomplete and you need a fact to build correctly — what counts as a qualified lead, which format a field should take, what the business rule actually is. Use this INSTEAD OF guessing or inventing a requirement. You are a builder: you do not decide what should be built, you find out.',
      parameters: {
        type: 'object',
        properties: {
          question: { type: 'string', description: 'One specific question. Not "what should I build" — something answerable.' },
          peer: { type: 'string', description: 'Which peer to ask. Omit for the first configured one.' },
          research: {
            type: 'boolean',
            description:
              'Only if the peer has nothing on record AND the user has approved paying for new research. Asking what a peer already knows is free; commissioning research costs money at their end and needs an explicit yes.',
          },
        },
        required: ['question'],
      },
      handler: async ({ question, peer, research }) => {
        // Spending is one of exactly two things that need a yes, and it does not
        // stop being spending because it happens on another AI's bill.
        if (research && !approvalCovers(approvals, APPROVAL_REQUIRED.COMMISSION_RESEARCH, peer ?? null)) {
          return {
            ok: false,
            needsApproval: APPROVAL_REQUIRED.COMMISSION_RESEARCH,
            approvalTarget: peer ?? null,
            error:
              `Answering "${String(question).slice(0, 120)}" would mean commissioning new research, which costs money at the peer's end. I need you to confirm before I do that — or tell me the answer yourself, which is free and faster.`,
            question,
          };
        }

        const res = await askPeer(store, {
          name: peer ?? null,
          question,
          // Free by default. A peer that has the answer gives it; a peer that
          // does not says so, and that is a question for the user rather than a
          // reason to start spending.
          extra: research ? { mode: 'research' } : { mode: 'stored', depth: 'none' },
          timeoutMs: research ? 25_000 : 20_000,
        });

        if (!res.ok) {
          return fail(
            `${res.error} Ask the user this question directly and wait — do not decide it yourself.`,
            { question },
          );
        }
        return ok({
          peer: res.peer,
          question,
          answer: res.answer,
          researched: Boolean(research),
          note: research
            ? null
            : 'This is what the peer already knew, which costs nothing. If the answer is that it has nothing on record, put the question to the user — do not commission research without their say-so.',
        });
      },
    },

    {
      name: 'list_peers',
      say: () => 'checking who I can ask',
      description: 'List the other AIs available to ask.',
      parameters: { type: 'object', properties: {} },
      handler: async () => ok({ peers: await listPeers(store) }),
    },

    {
      name: 'recall',
      say: () => 'checking what I already know about you',
      description: 'List what you already know about this user. Everything here is also in your prompt; use this only to get ids for correcting a fact.',
      parameters: { type: 'object', properties: {} },
      handler: async () => ok({ facts: await activeFacts(store) }),
    },
  ];

  /**
   * One guard for every tool, at the seam rather than repeated in twenty
   * handlers.
   *
   * Each handler destructures its arguments, so being called with null or a
   * string throws a TypeError before a single line of the tool runs — and a
   * throw here is not a refusal, it is a turn ending with a stack trace. The
   * pipeline and the MCP door both pass `?? {}` today, which means this has
   * never fired; the day something else calls a tool it will, and "the model
   * sent junk" should read as an answer, not a crash.
   */
  return tools.map((tool) => ({
    ...tool,
    handler: async (args) => {
      const safe = args && typeof args === 'object' && !Array.isArray(args) ? args : {};
      try {
        return await tool.handler(safe);
      } catch (err) {
        return fail(`${tool.name} could not run: ${err.message}`);
      }
    },
    say: (args) => {
      try {
        return tool.say?.(args && typeof args === 'object' ? args : {}) ?? null;
      } catch {
        return null;
      }
    },
  }));
}

/** "n8n-nodes-base.googleSheets" -> "Google Sheets", for things you read. */
function prettyNode(type) {
  if (!type) return 'that node';
  return String(type)
    .split('.')
    .pop()
    .replace(/Trigger$/, ' trigger')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/^./, (c) => c.toUpperCase());
}

// ---------------------------------------------------------------------------

/** Which nodes in a workflow can change something in the outside world. */
export function writeNodesIn(workflow) {
  const out = [];
  for (const node of workflow?.nodes ?? []) {
    if (!node || node.disabled) continue;
    const params = node.parameters ?? {};
    if (
      isWriteOperation({
        type: node.type,
        resource: typeof params.resource === 'string' ? params.resource : null,
        operation: typeof params.operation === 'string' ? params.operation : null,
        // The HTTP method is the difference between reading an API and posting
        // to it, and no operation discriminator carries it.
        parameters: params,
      })
    ) {
      out.push(node.name);
    }
  }
  return out;
}

/**
 * Nodes whose reach cannot be read off their parameters — a Code node can call
 * anything. They are not disabled, because disabling every one would leave a
 * dry run proving nothing; they are named, because "nothing was sent" must not
 * be claimed about a node nobody can inspect.
 */
export function opaqueNodesIn(workflow) {
  return (workflow?.nodes ?? [])
    .filter((n) => n && !n.disabled && isOpaqueNode(n.type))
    .map((n) => n.name);
}

function summariseExecution(execution) {
  const resultData = execution?.data?.resultData ?? {};
  const runData = resultData.runData ?? {};
  const nodes = Object.entries(runData).map(([name, runs]) => {
    const run = runs?.[0] ?? {};
    const items = run.data?.main?.[0] ?? [];
    return {
      node: name,
      status: run.error ? 'error' : 'ok',
      error: run.error?.message ?? null,
      itemCount: Array.isArray(items) ? items.length : null,
      firstItem: Array.isArray(items) && items[0] ? JSON.stringify(items[0].json ?? items[0]).slice(0, 600) : null,
    };
  });
  return {
    id: execution?.id,
    workflowId: execution?.workflowId,
    status: execution?.status,
    startedAt: execution?.startedAt,
    stoppedAt: execution?.stoppedAt,
    lastNodeExecuted: resultData.lastNodeExecuted ?? null,
    nodes,
  };
}

/**
 * Dry run: prove the data path without letting anything reach a real system.
 *
 * The write nodes are disabled rather than removed, so the shape of the
 * workflow is unchanged and the report can say exactly what each one would
 * have received. The test copy is a separate workflow — the original is never
 * modified to run a test.
 */
async function dryRun({ n8n, store, onStatus, prefs = {}, id, pinData }) {
  if (!n8n) return fail('No n8n connection is configured.');

  let original;
  try {
    original = await n8n.getWorkflow(id);
  } catch (e) {
    return fail(`Could not fetch workflow ${id}: ${e.message}`);
  }
  // A 200 with an empty body is a thing real instances do behind a proxy.
  if (!original || typeof original !== 'object' || !Array.isArray(original.nodes)) {
    return fail(`n8n returned nothing usable for workflow ${id}, so there is nothing I can safely copy and test.`);
  }

  // Disabling writes is the default and stays on unless deliberately turned
  // off in settings. With it off, a dry run can reach real systems.
  const disableWrites = prefs.dryRunDisablesWrites !== false;
  const writers = disableWrites ? writeNodesIn(original) : [];
  // Named, not disabled. A Code node can call anything, and claiming "nothing
  // was sent" while one runs would be a guarantee nobody can actually make.
  const opaque = opaqueNodesIn(original).filter((n) => !writers.includes(n));
  onStatus(writers.length ? `Disabling ${writers.length} write node(s) for the dry run…` : 'No write nodes to disable.');

  const testWorkflow = {
    name: `${original.name} [${prefs.testTagPrefix ?? 'assistant'} test]`,
    nodes: (original.nodes ?? []).map((n) => (writers.includes(n.name) ? { ...n, disabled: true } : { ...n })),
    connections: original.connections ?? {},
    settings: original.settings ?? {},
  };
  if (pinData && Object.keys(pinData).length) testWorkflow.pinData = pinData;

  let created;
  try {
    created = await n8n.createWorkflow(testWorkflow);
  } catch (e) {
    return fail(`Could not create the test copy: ${e.message}`);
  }

  const testId = created.workflow?.id;
  if (!testId) return fail('n8n did not say what id the test copy got, so I cannot run it or tell you where it is.');
  onStatus(`Running test copy ${testId}…`);

  const run = await n8n.runWorkflow(testId);

  let execution = null;
  let readError = null;
  if (run.ran) {
    try {
      execution = await n8n.latestExecution(testId);
    } catch (e) {
      readError = e.message;
    }
  }

  // Put the copy away. Left visible, every dry run adds another "[assistant
  // test]" workflow to the list — after twenty builds the instance is mostly
  // test copies. Archived, not deleted: it is still there, still readable,
  // still restorable, just not in the way.
  let retired;
  try {
    retired = await n8n.archiveWorkflow(testId);
  } catch (e) {
    retired = { archived: false, error: e.message };
  }

  const assessment = run.ran
    ? assessExecution({ execution, readError, disabledWriteNodes: writers })
    : {
        verdict: 'unconfirmed',
        headline: 'Could not run it from the API',
        detail: run.error,
        evidence: { testWorkflowId: testId, tried: run.tried },
      };

  return ok({
    testWorkflowId: testId,
    testWorkflowName: testWorkflow.name,
    disabledWriteNodes: writers,
    ran: run.ran,
    assessment,
    execution: execution ? summariseExecution(execution) : null,
    retired,
    wouldHaveSent: writers.length
      ? `These nodes were disabled and sent nothing: ${writers.join(', ')}. Their input is visible in the execution of the node feeding them.`
      : null,
    couldNotBeCertainAbout: opaque.length
      ? `${opaque.join(', ')} can reach anything from inside their own code, so I cannot promise those sent nothing. Everything I could identify as sending was switched off.`
      : null,
    note:
      retired?.archived === true
        ? `The test copy (${testId}) has been archived so it is out of your workflow list. Nothing was deleted — it is under Archived in n8n, with its execution history.`
        : `The test copy (${testId}) is still in your workflow list, inactive: ${retired?.reason ?? retired?.error ?? 'archiving it did not confirm'}. Nothing was deleted.`,
  });
}

/**
 * Probe workflow: the only honest way to get real picker values without the
 * user's tokens ever leaving n8n. Builds a minimal read-only workflow, runs it,
 * reads the output, then archives it.
 */
async function runProbe({ n8n, store, onStatus, prefs = {}, nodeType, resource, operation, credentialType, credentialId, parameters }) {
  if (!n8n) return fail('No n8n connection is configured.');

  const catalogNode = getNode(nodeType);
  if (!catalogNode) return fail(`Unknown node type "${nodeType}".`);

  const op = operation ?? 'getAll';
  if (isWriteOperation({ type: nodeType, resource: resource ?? null, operation: op })) {
    return fail(`Refusing to probe with operation "${op}" — probes are read-only. Use a list/get operation.`);
  }

  const probe = {
    name: `[${prefs.testTagPrefix ?? 'assistant'} probe] ${catalogNode.displayName} ${resource ?? ''} ${op}`.trim(),
    nodes: [
      { id: 'trigger', name: 'Start', type: 'n8n-nodes-base.manualTrigger', typeVersion: 1, position: [0, 0], parameters: {} },
      {
        id: 'probe',
        name: 'List',
        type: nodeType,
        typeVersion: catalogNode.version ?? 1,
        position: [220, 0],
        parameters: { ...(resource ? { resource } : {}), operation: op, returnAll: false, limit: 100, ...(parameters ?? {}) },
        credentials: { [credentialType]: { id: credentialId, name: credentialId } },
      },
    ],
    connections: { Start: { main: [[{ node: 'List', type: 'main', index: 0 }]] } },
    settings: {},
  };

  onStatus('Running a read-only probe against your credential…');

  let created;
  try {
    created = await n8n.createWorkflow(probe);
  } catch (e) {
    return fail(`Could not create the probe workflow: ${e.message}`);
  }
  const probeId = created.workflow?.id;
  if (!probeId) return fail('n8n did not say what id the probe got, so I cannot run it or clean it up. I will not guess a value instead.');

  const run = await n8n.runWorkflow(probeId);
  let execution = null;
  let readError = null;
  if (run.ran) {
    try {
      execution = await n8n.latestExecution(probeId);
    } catch (e) {
      readError = e.message;
    }
  }

  // Always retire the probe, whatever happened. Archive, never delete.
  let retired = null;
  try {
    retired = await n8n.archiveWorkflow(probeId);
  } catch (e) {
    retired = { archived: false, error: e.message };
  }

  if (!run.ran) {
    return fail(
      `The probe could not be run from the API (${run.error}). I have no real values, so I will not guess one — pick the value in n8n and tell me, or run the probe workflow manually.`,
      { probeWorkflowId: probeId, retired },
    );
  }

  const assessment = assessExecution({ execution, readError });
  if (assessment.verdict !== 'worked') {
    return fail(`The probe ran but I could not read real values back: ${assessment.detail}`, { probeWorkflowId: probeId, assessment, retired });
  }

  const runData = execution?.data?.resultData?.runData?.List?.[0]?.data?.main?.[0] ?? [];
  const values = runData.map((item) => item.json ?? item).slice(0, 100);

  return ok({
    values,
    count: values.length,
    probeWorkflowId: probeId,
    retired,
    note: 'These are real values read through your credential inside n8n. Use one of them verbatim; do not adapt or shorten an id.',
  });
}
