/**
 * The tool registry.
 *
 * This is built in exactly ONE place and every entry point calls this function.
 * tests/entrypoint-parity.test.js fails the build if any entry point is ever
 * handed a different set of tools or a different schema for the same tool —
 * because the day the web UI can do something the API cannot, there are two
 * assistants with different powers and nobody notices until one of them does
 * something the other would have refused.
 *
 * Note what is absent: there is no delete tool, of any kind, for any resource.
 * Not for workflows, not for executions, not for credentials.
 */

import { searchNodes, getNodeSchema, catalogMeta, isWriteOperation, getNode } from './nodeIndex.js';
import { validateWorkflow } from './validate.js';
import { assessExecution } from './assess.js';

/** Actions that need explicit confirmation: sending and spending. Nothing else. */
export const APPROVAL_REQUIRED = {
  ACTIVATE: 'activate_workflow',
  ENABLE_WRITES: 'enable_write_nodes',
};

const ok = (data) => ({ ok: true, ...data });
const fail = (error, extra = {}) => ({ ok: false, error, ...extra });

/**
 * @param {object} ctx
 * @param {object} ctx.n8n         n8n client, or null if not configured
 * @param {object} ctx.store
 * @param {string[]} ctx.approvals action keys the user has explicitly approved this turn
 * @param {(s:string)=>void} ctx.onStatus
 */
export function buildToolRegistry(ctx) {
  const { n8n = null, store, approvals = [], onStatus = () => {} } = ctx;

  const needsN8n = () =>
    fail('No n8n connection is configured. Paste your n8n base URL and API key in Settings first.');

  const tools = [
    {
      name: 'search_nodes',
      description:
        'Search the n8n node index for nodes matching a query. Returns each node type with its resource/operation discriminators. ALWAYS call this before using any node — never write a node type from memory.',
      parameters: {
        type: 'object',
        properties: {
          query: { type: 'string', description: 'What the node should do, e.g. "slack send message" or "google sheets append".' },
          limit: { type: 'number', description: 'Max results, default 12.' },
        },
        required: ['query'],
      },
      handler: async ({ query, limit }) => {
        const results = searchNodes(query, { limit: limit ?? 12 });
        if (!results.length) {
          return ok({
            results: [],
            note: `Nothing in the index matches "${query}". The index holds ${catalogMeta().nodeCount} nodes. Do not invent a node type — try different words, or tell the user this node is not available.`,
          });
        }
        return ok({ results });
      },
    },

    {
      name: 'get_node_schema',
      description:
        'Get the EXACT parameter definitions for a node + resource + operation, as generated by n8n itself. You must call this for every node you plan to use before writing its parameters. Inventing a parameter name will be rejected by the validator.',
      parameters: {
        type: 'object',
        properties: {
          nodeType: { type: 'string', description: 'Full node type, e.g. "n8n-nodes-base.slack".' },
          resource: { type: 'string', description: 'Resource discriminator, e.g. "message".' },
          operation: { type: 'string', description: 'Operation discriminator, e.g. "post".' },
        },
        required: ['nodeType'],
      },
      handler: async ({ nodeType, resource, operation }) => {
        const schema = getNodeSchema({ type: nodeType, resource: resource ?? null, operation: operation ?? null });
        if (!schema.found) return fail(schema.error, { available: schema.available });

        // Trim: the model needs the type text for the operations it asked
        // about, and sending all of them for a node like Slack is 100KB.
        const trimmed = schema.operations.slice(0, 3).map((o) => ({
          ...o,
          typeDefinition: o.typeDefinition?.slice(0, 24000) ?? null,
        }));
        return ok({ ...schema, operations: trimmed, truncated: schema.operations.length > 3 });
      },
    },

    {
      name: 'list_credentials',
      description:
        'List the credentials that exist in the n8n instance (names, ids and types only — never secrets). Use a real credential id; never invent one.',
      parameters: { type: 'object', properties: {} },
      handler: async () => {
        if (!n8n) return needsN8n();
        try {
          const res = await n8n.listCredentials();
          const items = (res?.data ?? res ?? []).map((c) => ({ id: c.id, name: c.name, type: c.type }));
          return ok({ credentials: items });
        } catch (e) {
          return fail(`Could not list credentials: ${e.message}`);
        }
      },
    },

    {
      name: 'list_workflows',
      description: 'List workflows in the n8n instance.',
      parameters: {
        type: 'object',
        properties: {
          limit: { type: 'number' },
          active: { type: 'boolean', description: 'Filter to only active or only inactive workflows.' },
        },
      },
      handler: async ({ limit, active }) => {
        if (!n8n) return needsN8n();
        try {
          const res = await n8n.listWorkflows({ limit: limit ?? 30, active: active ?? null });
          const items = (res?.data ?? []).map((w) => ({
            id: w.id,
            name: w.name,
            active: w.active,
            isArchived: w.isArchived ?? false,
            updatedAt: w.updatedAt,
            nodeCount: w.nodes?.length ?? null,
          }));
          return ok({ workflows: items });
        } catch (e) {
          return fail(`Could not list workflows: ${e.message}`);
        }
      },
    },

    {
      name: 'get_workflow',
      description: 'Fetch one workflow in full, including its nodes and connections.',
      parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] },
      handler: async ({ id }) => {
        if (!n8n) return needsN8n();
        try {
          return ok({ workflow: await n8n.getWorkflow(id) });
        } catch (e) {
          return fail(`Could not fetch workflow ${id}: ${e.message}`);
        }
      },
    },

    {
      name: 'validate_workflow',
      description:
        'Validate workflow JSON before saving it. Checks node types, parameter names against the real schemas, required parameters, ungrounded picker values, and the connection graph. ALWAYS call this before save_workflow.',
      parameters: {
        type: 'object',
        properties: { workflow: { type: 'object', description: 'The full workflow JSON: { name, nodes, connections }.' } },
        required: ['workflow'],
      },
      handler: async ({ workflow }) => {
        const result = await validateWorkflow(workflow);
        return ok(result);
      },
    },

    {
      name: 'ground_options',
      description:
        'Get the REAL list of values for a picker parameter (Slack channels, Google Sheets tabs, and so on) by running a temporary read-only probe workflow in n8n against the credential. Use this instead of guessing any id. The probe is archived afterwards and never deletes anything.',
      parameters: {
        type: 'object',
        properties: {
          nodeType: { type: 'string' },
          resource: { type: 'string' },
          operation: { type: 'string', description: 'A read-only list operation, e.g. "getAll".' },
          credentialType: { type: 'string' },
          credentialId: { type: 'string' },
          parameters: { type: 'object', description: 'Extra parameters the list operation needs.' },
        },
        required: ['nodeType', 'credentialType', 'credentialId'],
      },
      handler: async (args) => runProbe({ n8n, store, onStatus, ...args }),
    },

    {
      name: 'save_workflow',
      description:
        'Create a new workflow (always inactive) or update an existing one. Updating snapshots the current version first so it is always recoverable. Never destroys anything.',
      parameters: {
        type: 'object',
        properties: {
          mode: { type: 'string', description: '"create" or "update".' },
          id: { type: 'string', description: 'Required when mode is "update".' },
          workflow: { type: 'object' },
          reason: { type: 'string', description: 'Why this change is being made — recorded with the snapshot.' },
        },
        required: ['mode', 'workflow'],
      },
      handler: async ({ mode, id, workflow, reason }) => {
        if (!n8n) return needsN8n();

        const validation = await validateWorkflow(workflow);
        if (!validation.valid) {
          return fail('Refusing to save: the workflow does not validate.', { validation });
        }

        // n8n rejects unknown top-level keys on write.
        const payload = {
          name: workflow.name,
          nodes: workflow.nodes,
          connections: workflow.connections ?? {},
          settings: workflow.settings ?? {},
        };

        try {
          if (mode === 'create') {
            onStatus('Creating workflow (inactive)…');
            const res = await n8n.createWorkflow(payload);
            return ok({
              created: true,
              id: res.workflow?.id,
              confirmed: res.confirmed,
              active: false,
              validation,
              note: res.confirmed
                ? 'Created and read back from n8n. It is inactive until you approve activating it.'
                : "Created, but reading it back did not confirm it — I can't yet promise it is there.",
            });
          }

          if (mode === 'update') {
            if (!id) return fail('mode "update" needs the workflow id.');
            onStatus('Snapshotting the current version before changing it…');
            const current = await n8n.getWorkflow(id);
            const snap = await store.snapshot({
              workflowId: id,
              name: current?.name ?? null,
              workflow: current,
              reason: reason ?? 'before update',
            });
            const res = await n8n.updateWorkflow(id, payload, { snapshotId: snap.id });
            return ok({
              updated: true,
              id,
              snapshotId: snap.id,
              confirmed: res.confirmed,
              validation,
              note: `Previous version saved as snapshot ${snap.id}; it can be restored at any time.`,
            });
          }

          return fail(`Unknown mode "${mode}".`);
        } catch (e) {
          return fail(`Save failed: ${e.message}`);
        }
      },
    },

    {
      name: 'dry_run_workflow',
      description:
        'Test a workflow WITHOUT touching real systems: every write-capable node is disabled, test data is pinned on the trigger, and the workflow is run. Reports what each node produced and exactly what the disabled write nodes WOULD have received.',
      parameters: {
        type: 'object',
        properties: {
          id: { type: 'string', description: 'Workflow id to dry run.' },
          pinData: { type: 'object', description: 'Test data to pin, keyed by trigger node name.' },
        },
        required: ['id'],
      },
      handler: async ({ id, pinData }) => dryRun({ n8n, store, onStatus, id, pinData }),
    },

    {
      name: 'list_failed_executions',
      description: 'List recent failed executions across the instance, newest first. Use this to find out what broke.',
      parameters: {
        type: 'object',
        properties: { limit: { type: 'number' }, workflowId: { type: 'string' } },
      },
      handler: async ({ limit, workflowId }) => {
        if (!n8n) return needsN8n();
        try {
          const res = await n8n.listExecutions({ status: 'error', limit: limit ?? 10, workflowId: workflowId ?? null });
          const items = (res?.data ?? []).map((e) => ({
            id: e.id,
            workflowId: e.workflowId,
            workflowName: e.workflowData?.name ?? null,
            status: e.status,
            startedAt: e.startedAt,
          }));
          return ok({ failures: items });
        } catch (e) {
          return fail(`Could not list executions: ${e.message}`);
        }
      },
    },

    {
      name: 'get_execution',
      description: 'Read one execution in full, including the error and which node failed.',
      parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] },
      handler: async ({ id }) => {
        if (!n8n) return needsN8n();
        try {
          const execution = await n8n.getExecution(id);
          const assessment = assessExecution({ execution });
          return ok({ execution: summariseExecution(execution), assessment });
        } catch (e) {
          return fail(`Could not read execution ${id}: ${e.message}`);
        }
      },
    },

    {
      name: 'set_workflow_active',
      description:
        'Activate or deactivate a workflow. Deactivating is always allowed. ACTIVATING a workflow that contains write-capable nodes requires the user to approve first, because activating it means it will start sending things.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' }, active: { type: 'boolean' } },
        required: ['id', 'active'],
      },
      handler: async ({ id, active }) => {
        if (!n8n) return needsN8n();
        try {
          if (active) {
            const wf = await n8n.getWorkflow(id);
            const writers = writeNodesIn(wf);
            if (writers.length && !approvals.includes(APPROVAL_REQUIRED.ACTIVATE)) {
              return {
                ok: false,
                needsApproval: APPROVAL_REQUIRED.ACTIVATE,
                error:
                  `Activating "${wf.name}" would let it send things for real via: ${writers.join(', ')}. ` +
                  'I need you to confirm before I do that.',
                writeNodes: writers,
              };
            }
          }
          const res = await n8n.setActive(id, active);
          return ok({
            requested: active,
            actual: res.actual,
            confirmed: res.confirmed,
            note: res.confirmed
              ? `Read back from n8n as active=${res.actual}.`
              : `n8n accepted the change but reads back as active=${res.actual}. I cannot confirm it took effect.`,
          });
        } catch (e) {
          return fail(`Could not change activation: ${e.message}`);
        }
      },
    },

    {
      name: 'archive_workflow',
      description:
        'Retire a workflow by deactivating and archiving it. This is the ONLY way to retire something — nothing is ever deleted, and it can be restored.',
      parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] },
      handler: async ({ id }) => {
        if (!n8n) return needsN8n();
        try {
          return ok(await n8n.archiveWorkflow(id));
        } catch (e) {
          return fail(`Could not archive: ${e.message}`);
        }
      },
    },

    {
      name: 'list_snapshots',
      description: 'List saved snapshots of previous workflow versions, so a change can be reviewed or rolled back.',
      parameters: { type: 'object', properties: { workflowId: { type: 'string' } } },
      handler: async ({ workflowId }) => ok({ snapshots: (await store.listSnapshots(workflowId ?? null)).map(({ workflow, ...rest }) => rest) }),
    },
  ];

  return tools;
}

// ---------------------------------------------------------------------------

/** Which nodes in a workflow can change something in the outside world. */
export function writeNodesIn(workflow) {
  const out = [];
  for (const node of workflow?.nodes ?? []) {
    if (node.disabled) continue;
    const params = node.parameters ?? {};
    if (
      isWriteOperation({
        type: node.type,
        resource: typeof params.resource === 'string' ? params.resource : null,
        operation: typeof params.operation === 'string' ? params.operation : null,
      })
    ) {
      out.push(node.name);
    }
  }
  return out;
}

function summariseExecution(execution) {
  const resultData = execution?.data?.resultData ?? {};
  const runData = resultData.runData ?? {};
  const nodes = Object.entries(runData).map(([name, runs]) => {
    const run = runs?.[0] ?? {};
    const items = run.data?.main?.[0] ?? [];
    return {
      node: name,
      status: run.error ? 'error' : 'ok',
      error: run.error?.message ?? null,
      itemCount: Array.isArray(items) ? items.length : null,
      firstItem: Array.isArray(items) && items[0] ? JSON.stringify(items[0].json ?? items[0]).slice(0, 600) : null,
    };
  });
  return {
    id: execution?.id,
    workflowId: execution?.workflowId,
    status: execution?.status,
    startedAt: execution?.startedAt,
    stoppedAt: execution?.stoppedAt,
    lastNodeExecuted: resultData.lastNodeExecuted ?? null,
    nodes,
  };
}

/**
 * Dry run: prove the data path without letting anything reach a real system.
 *
 * The write nodes are disabled rather than removed, so the shape of the
 * workflow is unchanged and the report can say exactly what each one would
 * have received. The test copy is a separate workflow — the original is never
 * modified to run a test.
 */
async function dryRun({ n8n, store, onStatus, id, pinData }) {
  if (!n8n) return fail('No n8n connection is configured.');

  let original;
  try {
    original = await n8n.getWorkflow(id);
  } catch (e) {
    return fail(`Could not fetch workflow ${id}: ${e.message}`);
  }

  const writers = writeNodesIn(original);
  onStatus(writers.length ? `Disabling ${writers.length} write node(s) for the dry run…` : 'No write nodes to disable.');

  const testWorkflow = {
    name: `${original.name} [test]`,
    nodes: (original.nodes ?? []).map((n) => (writers.includes(n.name) ? { ...n, disabled: true } : { ...n })),
    connections: original.connections ?? {},
    settings: original.settings ?? {},
  };
  if (pinData && Object.keys(pinData).length) testWorkflow.pinData = pinData;

  let created;
  try {
    created = await n8n.createWorkflow(testWorkflow);
  } catch (e) {
    return fail(`Could not create the test copy: ${e.message}`);
  }

  const testId = created.workflow?.id;
  onStatus(`Running test copy ${testId}…`);

  const run = await n8n.runWorkflow(testId);

  let execution = null;
  let readError = null;
  if (run.ran) {
    try {
      execution = await n8n.latestExecution(testId);
    } catch (e) {
      readError = e.message;
    }
  }

  const assessment = run.ran
    ? assessExecution({ execution, readError, disabledWriteNodes: writers })
    : {
        verdict: 'unconfirmed',
        headline: 'Could not run it from the API',
        detail: run.error,
        evidence: { testWorkflowId: testId, tried: run.tried },
      };

  return ok({
    testWorkflowId: testId,
    testWorkflowName: testWorkflow.name,
    disabledWriteNodes: writers,
    ran: run.ran,
    assessment,
    execution: execution ? summariseExecution(execution) : null,
    wouldHaveSent: writers.length
      ? `These nodes were disabled and sent nothing: ${writers.join(', ')}. Their input is visible in the execution of the node feeding them.`
      : null,
    note: 'The test copy is left in place, inactive, so you can inspect it. Nothing was deleted.',
  });
}

/**
 * Probe workflow: the only honest way to get real picker values without the
 * user's tokens ever leaving n8n. Builds a minimal read-only workflow, runs it,
 * reads the output, then archives it.
 */
async function runProbe({ n8n, store, onStatus, nodeType, resource, operation, credentialType, credentialId, parameters }) {
  if (!n8n) return fail('No n8n connection is configured.');

  const catalogNode = getNode(nodeType);
  if (!catalogNode) return fail(`Unknown node type "${nodeType}".`);

  const op = operation ?? 'getAll';
  if (isWriteOperation({ type: nodeType, resource: resource ?? null, operation: op })) {
    return fail(`Refusing to probe with operation "${op}" — probes are read-only. Use a list/get operation.`);
  }

  const probe = {
    name: `[assistant probe] ${catalogNode.displayName} ${resource ?? ''} ${op}`.trim(),
    nodes: [
      { id: 'trigger', name: 'Start', type: 'n8n-nodes-base.manualTrigger', typeVersion: 1, position: [0, 0], parameters: {} },
      {
        id: 'probe',
        name: 'List',
        type: nodeType,
        typeVersion: catalogNode.version ?? 1,
        position: [220, 0],
        parameters: { ...(resource ? { resource } : {}), operation: op, returnAll: false, limit: 100, ...(parameters ?? {}) },
        credentials: { [credentialType]: { id: credentialId, name: credentialId } },
      },
    ],
    connections: { Start: { main: [[{ node: 'List', type: 'main', index: 0 }]] } },
    settings: {},
  };

  onStatus('Running a read-only probe against your credential…');

  let created;
  try {
    created = await n8n.createWorkflow(probe);
  } catch (e) {
    return fail(`Could not create the probe workflow: ${e.message}`);
  }
  const probeId = created.workflow?.id;

  const run = await n8n.runWorkflow(probeId);
  let execution = null;
  let readError = null;
  if (run.ran) {
    try {
      execution = await n8n.latestExecution(probeId);
    } catch (e) {
      readError = e.message;
    }
  }

  // Always retire the probe, whatever happened. Archive, never delete.
  let retired = null;
  try {
    retired = await n8n.archiveWorkflow(probeId);
  } catch (e) {
    retired = { archived: false, error: e.message };
  }

  if (!run.ran) {
    return fail(
      `The probe could not be run from the API (${run.error}). I have no real values, so I will not guess one — pick the value in n8n and tell me, or run the probe workflow manually.`,
      { probeWorkflowId: probeId, retired },
    );
  }

  const assessment = assessExecution({ execution, readError });
  if (assessment.verdict !== 'worked') {
    return fail(`The probe ran but I could not read real values back: ${assessment.detail}`, { probeWorkflowId: probeId, assessment, retired });
  }

  const runData = execution?.data?.resultData?.runData?.List?.[0]?.data?.main?.[0] ?? [];
  const values = runData.map((item) => item.json ?? item).slice(0, 100);

  return ok({
    values,
    count: values.length,
    probeWorkflowId: probeId,
    retired,
    note: 'These are real values read through your credential inside n8n. Use one of them verbatim; do not adapt or shorten an id.',
  });
}
