import {Check, Copy, Laptop} from 'lucide-react';
import {useEffect, useState} from 'react';

/**
 * The token the laptop needs, and whether it has been heard from.
 *
 * This is the one secret in the whole app that is shown in full, and it is
 * worth saying why. Every other key is typed into Grace and never sent back —
 * there is no reason for a browser to hold your Gemini key. This one is
 * generated by her and has to be carried to another machine, so displaying it
 * is the entire point. It grants exactly two things: waking a games console
 * and putting it back to sleep.
 */

interface Status {
  token: string;
  online: boolean;
  seenAt: string | null;
  state: {found: boolean; status: string | null; name: string | null} | null;
}

function ago(iso: string): string {
  const minutes = Math.round((Date.now() - new Date(iso).getTime()) / 60_000);
  if (minutes < 1) return 'a moment ago';
  if (minutes < 60) return `${minutes} minutes ago`;
  const hours = Math.round(minutes / 60);
  return hours < 24 ? `${hours} hours ago` : `${Math.round(hours / 24)} days ago`;
}

export function Bridge() {
  const [status, setStatus] = useState<Status | null>(null);
  const [copied, setCopied] = useState(false);
  const [shown, setShown] = useState(false);

  useEffect(() => {
    const load = () =>
      fetch('/api/bridge-status')
        .then((response) => (response.ok ? response.json() : null))
        .then((body: Status | null) => body && setStatus(body))
        .catch(() => {});

    load();
    const timer = window.setInterval(load, 20_000);
    return () => window.clearInterval(timer);
  }, []);

  if (!status) return null;

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(status.token);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard access is refused in plenty of ordinary situations. Showing
      // the token is the fallback, and it is one tap away.
      setShown(true);
    }
  };

  return (
    <div className="space-y-2">
      <div className="flex items-center gap-2">
        <span
          className={`h-1.5 w-1.5 rounded-full ${
            status.online ? 'bg-ice' : 'bg-mist/30'
          }`}
        />
        <span className="text-xs text-slate-300">
          {status.online ? 'The laptop is listening' : 'No laptop is running the bridge'}
        </span>
      </div>

      {status.online ? (
        <p className="text-[0.65rem] leading-relaxed text-mist/60">
          {status.state?.found
            ? `${status.state.name ?? 'The console'} is ${
                status.state.status === 'AWAKE' ? 'on' : 'in rest mode'
              }. Ask her to turn it on or off.`
            : 'No console is answering on that network yet.'}
        </p>
      ) : (
        <p className="text-[0.65rem] leading-relaxed text-mist/60">
          She can only reach the PlayStation through a program on a machine in
          the same house. It is in <span className="font-mono">bridge/</span> in
          her repository, with instructions.
          {status.seenAt && ` Last heard from ${ago(status.seenAt)}.`}
        </p>
      )}

      <div className="flex gap-1.5">
        <button
          type="button"
          onClick={() => void copy()}
          className="flex items-center gap-1.5 rounded-lg border border-ice/40 bg-ice/15 px-3 py-1.5 text-xs text-ice transition hover:bg-ice/25">
          {copied ? <Check size={12} /> : <Copy size={12} />}
          {copied ? 'Copied' : 'Copy the token'}
        </button>
        <button
          type="button"
          onClick={() => setShown((open) => !open)}
          className="flex items-center gap-1.5 rounded-lg border border-edge px-3 py-1.5 text-xs text-mist transition hover:text-slate-200">
          <Laptop size={12} />
          {shown ? 'Hide' : 'Show'}
        </button>
      </div>

      {shown && (
        <p className="break-all rounded-lg border border-edge bg-surface px-2.5 py-2 font-mono text-[0.65rem] text-slate-300">
          {status.token}
        </p>
      )}

      <p className="text-[0.6rem] leading-relaxed text-mist/40">
        This one is meant to be copied — it is how the laptop proves it is
        yours. It can wake the console and put it to sleep, and nothing else.
      </p>
    </div>
  );
}
