import {Check, Copy, Download, Laptop, RefreshCw} from 'lucide-react';
import {useEffect, useState} from 'react';

/**
 * The token the laptop needs, and whether it has been heard from.
 *
 * This is the one secret in the whole app that is shown in full, and it is
 * worth saying why. Every other key is typed into Grace and never sent back —
 * there is no reason for a browser to hold your Gemini key. This one is
 * generated by her and has to be carried to another machine, so displaying it
 * is the entire point. It grants exactly two things: waking a games console
 * and putting it back to sleep.
 */

interface Status {
  token: string;
  online: boolean;
  seenAt: string | null;
  state: {found: boolean; status: string | null; name: string | null} | null;
}

function ago(iso: string): string {
  const minutes = Math.round((Date.now() - new Date(iso).getTime()) / 60_000);
  if (minutes < 1) return 'a moment ago';
  if (minutes < 60) return `${minutes} minutes ago`;
  const hours = Math.round(minutes / 60);
  return hours < 24 ? `${hours} hours ago` : `${Math.round(hours / 24)} days ago`;
}

export function Bridge() {
  const [status, setStatus] = useState<Status | null>(null);
  const [copied, setCopied] = useState(false);
  const [shown, setShown] = useState(false);
  const [rolled, setRolled] = useState(false);

  useEffect(() => {
    const load = () =>
      fetch('/api/bridge-status')
        .then((response) => (response.ok ? response.json() : null))
        .then((body: Status | null) => body && setStatus(body))
        .catch(() => {});

    load();
    const timer = window.setInterval(load, 20_000);
    return () => window.clearInterval(timer);
  }, []);

  const roll = async () => {
    const response = await fetch('/api/bridge-roll', {method: 'POST'});
    if (!response.ok) return;
    const body = (await response.json()) as {token: string};
    // Shown straight away, because the next thing to do is carry it to the
    // laptop — and the laptop is offline from this moment until you do.
    setStatus((was) => (was ? {...was, token: body.token} : was));
    setShown(true);
    setRolled(true);
  };

  if (!status) return null;

  // The exact line to run, with her own address and the token already in it.
  const command = `node bridge.mjs ${window.location.origin} ${status.token}`;

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(command);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard access is refused in plenty of ordinary situations. Showing
      // the token is the fallback, and it is one tap away.
      setShown(true);
    }
  };

  return (
    <div className="space-y-2">
      <div className="flex items-center gap-2">
        <span
          className={`h-1.5 w-1.5 rounded-full ${
            status.online ? 'bg-ice' : 'bg-mist/30'
          }`}
        />
        <span className="text-xs text-slate-300">
          {status.online ? 'The laptop is listening' : 'No laptop is running the bridge'}
        </span>
      </div>

      {status.online ? (
        <p className="text-[0.65rem] leading-relaxed text-mist/60">
          {status.state?.found
            ? `${status.state.name ?? 'The console'} is ${
                status.state.status === 'AWAKE' ? 'on' : 'in rest mode'
              }. Ask her to turn it on or off.`
            : 'No console is answering on that network yet.'}
        </p>
      ) : (
        <p className="text-[0.65rem] leading-relaxed text-mist/60">
          She can only reach the PlayStation through a program on a machine in
          the same house. Download it below, then run the command in a terminal
          on the laptop that stays on.
          {status.seenAt && ` Last heard from ${ago(status.seenAt)}.`}
        </p>
      )}

      <div className="flex gap-1.5">
        <a
          href="/bridge.mjs"
          download="bridge.mjs"
          className="flex items-center gap-1.5 rounded-lg border border-ice/40 bg-ice/15 px-3 py-1.5 text-xs text-ice transition hover:bg-ice/25">
          <Download size={12} />
          Download the bridge
        </a>
        <button
          type="button"
          onClick={() => void copy()}
          className="flex items-center gap-1.5 rounded-lg border border-edge px-3 py-1.5 text-xs text-mist transition hover:text-slate-200">
          {copied ? <Check size={12} /> : <Copy size={12} />}
          {copied ? 'Copied' : 'Copy command'}
        </button>
      </div>

      {/* The whole command, token and all. Nobody should have to assemble
          this by hand from three places on a laptop they cannot install
          anything on. */}
      <button
        type="button"
        onClick={() => setShown((open) => !open)}
        className="flex items-center gap-1.5 text-[0.62rem] text-mist/50 transition hover:text-mist">
        <Laptop size={11} />
        {shown ? 'Hide the command' : 'Show the command to run'}
      </button>

      {shown && (
        <p className="break-all rounded-lg border border-edge bg-surface px-2.5 py-2 font-mono text-[0.65rem] leading-relaxed text-slate-300">
          {command}
        </p>
      )}

      <button
        type="button"
        onClick={() => void roll()}
        className="flex items-center gap-1.5 text-[0.6rem] text-mist/40 transition hover:text-rose-300">
        <RefreshCw size={10} />
        {rolled ? 'Replaced — run the new command on the laptop' : 'Replace the token'}
      </button>

      <p className="text-[0.6rem] leading-relaxed text-mist/40">
        The token in that command is how the laptop proves it is yours. It can
        wake the console and put it to sleep, and nothing else. Replacing it
        stops the laptop until you run the new command there — which is what to
        do if it has been read over your shoulder or left in a screenshot.
      </p>
    </div>
  );
}
