#!/usr/bin/env node
/**
 * Stamps a build id into two places that are served by different mechanisms:
 *
 *   build.json          imported by api/health.js — proves which SERVER is live
 *   public/build.json   a static asset — proves which FRONTEND is live
 *
 * They are written from the same value in the same run. If the two ever
 * disagree in production, you are looking at a stale deployment of one half,
 * which is otherwise invisible: a server-only change leaves the frontend
 * bundle byte-identical and nothing on the page looks different.
 */

import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function gitSha() {
  // Vercel exposes the commit sha in env; git may not be available in the
  // build container, so try env first and fall back rather than failing.
  const fromEnv = process.env.VERCEL_GIT_COMMIT_SHA;
  if (fromEnv) return fromEnv.slice(0, 12);
  try {
    return execSync('git rev-parse --short=12 HEAD', { cwd: ROOT, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    return 'nogit';
  }
}

const build = {
  buildId: `${gitSha()}-${Date.now().toString(36)}`,
  commit: gitSha(),
  builtAt: new Date().toISOString(),
  env: process.env.VERCEL_ENV ?? 'local',
};

// Written as a JS module, not JSON, so it is a static import in api/health.js
// and Vercel's dependency tracing bundles it automatically. A dynamic JSON
// import gets missed by tracing and the deployed function reports "unstamped"
// while looking perfectly healthy.
fs.writeFileSync(
  path.join(ROOT, 'core', 'build.js'),
  `// Generated by scripts/stamp-build.mjs — do not edit.\nexport default ${JSON.stringify(build, null, 2)};\n`,
);
fs.mkdirSync(path.join(ROOT, 'public'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'public', 'build.json'), JSON.stringify(build, null, 2));

console.log(`stamped build ${build.buildId}`);
