#!/usr/bin/env node
/**
 * Stamps a build id into two places served by different mechanisms:
 *
 *   core/build.js     imported by api/health.js — proves which SERVER is live
 *   public/build.json a static asset            — proves which FRONTEND is live
 *
 * Written from the same value in the same run. If the two ever disagree in
 * production you are looking at a stale deployment of one half, which is
 * otherwise invisible: a server-only change leaves the frontend bundle
 * byte-identical and nothing on the page looks any different.
 *
 * Also generates the vercel.json headers block from core/headers.js, so the
 * CDN and the function cannot drift apart.
 */

import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { vercelHeaderEntries } from '../core/headers.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function gitSha() {
  // Vercel exposes the commit sha in env; git may not exist in the build
  // container, so try env first and fall back rather than failing the build.
  const fromEnv = process.env.VERCEL_GIT_COMMIT_SHA;
  if (fromEnv) return fromEnv.slice(0, 12);
  try {
    return execSync('git rev-parse --short=12 HEAD', { cwd: ROOT, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    return 'nogit';
  }
}

const sha = gitSha();
const build = {
  name: 'selena',
  buildId: `${sha}-${Date.now().toString(36)}`,
  commit: sha,
  builtAt: new Date().toISOString(),
  env: process.env.VERCEL_ENV ?? 'local',
};

// Written as a JS module rather than JSON so it is a static import in
// api/health.js and Vercel's dependency tracing bundles it automatically. A
// dynamic JSON import gets missed by tracing and the deployed function reports
// "unstamped" while looking perfectly healthy.
fs.writeFileSync(
  path.join(ROOT, 'core', 'build.js'),
  `// Generated by scripts/stamp-build.mjs — do not edit.\nexport default ${JSON.stringify(build, null, 2)};\n`,
);

fs.mkdirSync(path.join(ROOT, 'public'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'public', 'build.json'), JSON.stringify(build, null, 2));

// Keep vercel.json's headers in step with core/headers.js. The test asserts
// they match; this is what makes that assertion easy to satisfy.
const vercelPath = path.join(ROOT, 'vercel.json');
const vercel = JSON.parse(fs.readFileSync(vercelPath, 'utf8'));
vercel.headers = [{ source: '/(.*)', headers: vercelHeaderEntries() }];
fs.writeFileSync(vercelPath, `${JSON.stringify(vercel, null, 2)}\n`);

console.log(`stamped build ${build.buildId}`);
