// Generated by scripts/stamp-build.mjs — do not edit.
export default {
  "name": "selena",
  "buildId": "9246d8726cad-msasd7w1",
  "commit": "9246d8726cad",
  "builtAt": "2026-08-01T19:50:23.281Z",
  "env": "local"
};
