// Generated by scripts/stamp-build.mjs — do not edit.
export default {
  "name": "selena",
  "buildId": "bbfc52a4132d-msc7ljmf",
  "commit": "bbfc52a4132d",
  "builtAt": "2026-08-02T19:44:32.151Z",
  "env": "local"
};
