// Generated by scripts/stamp-build.mjs — do not edit.
export default {
  "name": "selena",
  "buildId": "7db2f446d7bd-msd67t4i",
  "commit": "7db2f446d7bd",
  "builtAt": "2026-08-03T11:53:37.842Z",
  "env": "local"
};
